import Head from 'next/head'
import { useContext, useEffect } from 'react'
import { Footer } from '../components/footer'
import { Homepage } from '../components/Homepage'
import MerchContext from '../context/MerchContext'
import { setCookies, getCookie, deleteCookie } from "cookies-next";
import { useRouter } from 'next/router'
import Cookies from 'js-cookie'

import Script from 'next/script'

export default function Home({ type }) {


  const { NavbarUserORcreator, setNavbarUserORcreator } = useContext(MerchContext)


  const router = useRouter()


  useEffect(() => {
    // setNavbarUserORcreator('user')
    let lastRoute = getCookie("lastRoute");
    if (typeof lastRoute !== 'undefined') {
      Cookies.remove('lastRoute')
      router.push(lastRoute)
    }

  }, []);



  return (
    <div className='relative' >
      <Head>
        <title>Merchandise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>




      <Homepage />

    </div>
  )
}
export async function getServerSideProps({ req, res }) {

  let role = getCookie("role", { req, res });

  if (typeof role !== 'undefined' && role === 'creator') {
    // return { redirect: { destination: "/dashboard" } };
    return {
      props: {
      }
    };

  } else {
    return {
      props: {
      }
    };
  }


}
